# Project Euler Solutions
# Problem 2 - Even Fibonacci numbers
''' Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

def evenFib(limit=100):
    fibs = [0,1]
    for i in range(2, limit + 1):
        one = fibs[-1]
        two = fibs[-2]
        if (one > 4000000 or two > 4000000):
            return fibs
        fibs.append(one + two)
    return fibs
        

if __name__ == "__main__":
    sum = 0
    fibList = evenFib()
    for i in fibList: 
        if i % 2 == 0: 
            sum += i
    print sum